#define VERIFY_CRASH 1
#define ASSERT_CRASH 1
#define VERBOSE 1
#define DEBUG_API 1
#define ENABLE_BOOT_LOADING 0//TODO IMPLEMENT NOT ALLOWING FILE LOADING ON BOOT FOR BETTER DEBUG TESTING AND GIT WORKFLOW